import Head from "next/head";
import { Inter } from "@next/font/google";
import Overview from "./Overview";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Overview />
    </>
  );
}
